# Generated by Django 6.1.1 on 2026-10-03 07:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import planner.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("longitude", models.FloatField(default=13.388)),
                ("latitude", models.FloatField(default=52.517)),
                ("geometry", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("school", "Schule"), ("university", "Hochschule")],
                        default="university",
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Berlin", max_length=80)),
                ("license_until", models.DateField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("unit_minutes", models.PositiveIntegerField(default=45)),
                ("exam_max_per_day", models.PositiveIntegerField(default=1)),
                ("exam_gap_hours", models.PositiveIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.cohort"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource", models.CharField(max_length=40)),
                ("rows", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("committed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("level", models.IntegerField(default=0)),
                ("background", models.FileField(blank=True, upload_to="floorplans/")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.building",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.institution"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.institution"
            ),
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Verwaltung"),
                            ("planner", "Planungsverantwortlich"),
                        ],
                        default="planner",
                        max_length=20,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("excluded_dates", models.JSONField(blank=True, default=list)),
                ("day_start", models.TimeField(default="08:00")),
                ("day_end", models.TimeField(default="18:00")),
                ("slot_minutes", models.PositiveIntegerField(default=30)),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True, default=planner.models.default_weekdays
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("learner", "Lernende"), ("teacher", "Lehrende")],
                        default="learner",
                        max_length=20,
                    ),
                ),
                ("availability", models.JSONField(blank=True, default=dict)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="people", to="planner.group"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("elective", models.BooleanField(default=False)),
                (
                    "target_mode",
                    models.CharField(
                        choices=[("weekly", "Pro Woche"), ("total", "Gesamtumfang")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("target_units", models.PositiveIntegerField(default=2)),
                ("duration_minutes", models.PositiveIntegerField(default=90)),
                (
                    "week_pattern",
                    models.CharField(
                        choices=[
                            ("all", "Jede Woche"),
                            ("A", "A-Woche"),
                            ("B", "B-Woche"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("teacher_assignments", models.JSONField(blank=True, default=list)),
                ("groups", models.ManyToManyField(blank=True, to="planner.group")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "learners",
                    models.ManyToManyField(
                        blank=True, related_name="enrolled_courses", to="planner.person"
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True, related_name="teaching_courses", to="planner.person"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.area"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.period"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("kind", models.CharField(default="teaching", max_length=20)),
                ("status", models.CharField(default="queued", max_length=30)),
                ("message", models.TextField(blank=True)),
                ("result", models.JSONField(default=list)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("resit", models.BooleanField(default=False)),
                ("equipment", models.JSONField(blank=True, default=list)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.course",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "learners",
                    models.ManyToManyField(
                        blank=True, related_name="exams", to="planner.person"
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True, related_name="supervised_exams", to="planner.person"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.plan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Display",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("show_teachers", models.BooleanField(default=False)),
                ("auto_scroll", models.BooleanField(default=True)),
                ("scroll_seconds", models.PositiveIntegerField(default=20)),
                ("active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                ("plans", models.ManyToManyField(blank=True, to="planner.plan")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.plan"
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="planner.program"
            ),
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("snapshot", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planner.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("polygon", models.JSONField(blank=True, default=list)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.floor"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoomBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("repeat_weekly", models.BooleanField(default=False)),
                ("repeat_until", models.DateField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                ("rooms", models.ManyToManyField(to="planner.room")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("locked", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.course",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.exam",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="planner.plan",
                    ),
                ),
                ("rooms", models.ManyToManyField(to="planner.room")),
                ("teachers", models.ManyToManyField(blank=True, to="planner.person")),
            ],
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="group_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="floor_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="building_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="area_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "institution"), name="unique_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="period_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="person_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="plan_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="exam_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="display",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="display_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="course_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="program_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="curriculum_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="cohort_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("plan", "number"), name="publication_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="room_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="roomblock",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="roomblock_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("end__gt", models.F("start"))),
                name="session_positive_duration",
            ),
        ),
    ]
