# Generated by Django 6.1.1 on 2026-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="block_days",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
