# Generated by Django 6.1.1 on 2026-10-03 08:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_course_block_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="day_end",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="period",
            name="day_start",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
