# Generated by Django 6.1.1 on 2026-10-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_alter_period_day_end_alter_period_day_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="view_mode",
            field=models.CharField(
                choices=[("week", "Woche"), ("today", "Heute"), ("tomorrow", "Morgen")],
                default="week",
                max_length=10,
            ),
        ),
    ]
