# Generated by Django 6.1.1 on 2026-10-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_display_view_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="entry_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.cohort",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="semester",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="program",
            name="duration_semesters",
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="program",
            name="total_credits",
            field=models.DecimalField(decimal_places=1, default=180, max_digits=6),
        ),
        migrations.CreateModel(
            name="StudyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.CharField(max_length=80)),
                ("duration_semesters", models.PositiveIntegerField(default=6)),
                (
                    "total_credits",
                    models.DecimalField(decimal_places=1, default=180, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("approved", "Freigegeben")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planner.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "credits",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="planner.module",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="planner.module"),
                ),
                (
                    "study_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modules",
                        to="planner.studyversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="study_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.studyversion",
            ),
        ),
        migrations.CreateModel(
            name="TeachingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("semester", models.PositiveIntegerField(default=1)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("lecture", "Vorlesung"),
                            ("seminar", "Seminar"),
                            ("exercise", "Übung"),
                            ("lab", "Labor"),
                            ("project", "Projekt"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        choices=[("weekly", "Pro Woche"), ("total", "Gesamtumfang")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("target_units", models.PositiveIntegerField(default=2)),
                ("duration_minutes", models.PositiveIntegerField(default=90)),
                ("block_days", models.PositiveIntegerField(default=1)),
                (
                    "week_pattern",
                    models.CharField(
                        choices=[
                            ("all", "Jede Woche"),
                            ("A", "A-Woche"),
                            ("B", "B-Woche"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("elective", models.BooleanField(default=False)),
                ("equipment", models.JSONField(blank=True, default=list)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_units",
                        to="planner.module",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="study_teaching_units",
                        to="planner.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="teaching_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.teachingunit",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("plan", "teaching_unit"), name="course_study_origin_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyversion",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="studyversion_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="module_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingunit",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="teachingunit_tenant_code"
            ),
        ),
    ]
