# Generated by Django 6.1.1 on 2026-10-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_cohort_entry_year_plan_cohort_plan_semester_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='course_study_origin_unique',
        ),
        migrations.AddField(
            model_name='course',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_deliveries', to='planner.group'),
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='group_mode',
            field=models.CharField(choices=[('combined', 'Gruppen gemeinsam'), ('per_group', 'Je Gruppe separat')], default='combined', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('study_group__isnull', True)), fields=('plan', 'teaching_unit'), name='course_study_combined_unique'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('plan', 'teaching_unit', 'study_group'), name='course_study_group_unique'),
        ),
    ]
