# Generated by Django 6.1.1 on 2026-10-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_course_course_study_origin_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='semester_credit_limit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cohort',
            name='semester_difficulty_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cohort',
            name='semester_weekly_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cohort',
            name='study_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='difficulty',
            field=models.PositiveIntegerField(choices=[(1, 'Leicht'), (2, 'Mittel'), (3, 'Anspruchsvoll')], default=2),
        ),
    ]
