# Generated by Django 6.1.1 on 2026-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_cohort_semester_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assessment_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='assessment_notes',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='module',
            name='assessment_type',
            field=models.CharField(choices=[('unspecified', 'Noch nicht festgelegt'), ('none', 'Keine eigene Prüfung'), ('exam', 'Klausur'), ('term_paper', 'Hausarbeit'), ('submission', 'Abgabe'), ('oral', 'Mündliche Prüfung'), ('presentation', 'Präsentation'), ('practical', 'Praktische Prüfung'), ('portfolio', 'Portfolio'), ('other', 'Sonstige Prüfungsleistung')], default='unspecified', max_length=20),
        ),
    ]
