# Generated by Django 6.1.1 on 2026-10-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0009_publication_overview_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="assessment_notes",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="exam",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("exam", "Klausur"),
                    ("oral", "Mündliche Prüfung"),
                    ("presentation", "Präsentation"),
                    ("practical", "Praktische Prüfung"),
                ],
                default="exam",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("exam", "Klausur"),
                            ("term_paper", "Hausarbeit"),
                            ("submission", "Abgabe"),
                            ("oral", "Mündliche Prüfung"),
                            ("presentation", "Präsentation"),
                            ("practical", "Praktische Prüfung"),
                            ("portfolio", "Portfolio"),
                            ("other", "Sonstige Prüfungsleistung"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "assessment_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assessment_notes",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("waived", "Entfällt für diesen Semesterplan"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.institution",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.module"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="planner.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="assessment_template",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="planned_exam",
                to="planner.assessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="assessment_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("plan", "module"), name="assessment_plan_module_unique"
            ),
        ),
    ]
