# Generated by Django 6.1.1 on 2026-10-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0010_exam_assessment_notes_exam_assessment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
